'''
meddict.py

Description: Lists important medical terms used in eliminating spam v. ok
tweets in main.py

Copyright (c) 2016, Manan Shah. All rights reserved. Redistribution and use in
source and binary forms, with or without modification, are not permitted without
retention of this notice.
'''
medterms = {
	'abdomen'		: ['stomach', 'tummy', 'belly'],
	'abrasion'		: ['scrape', 'scratch'],
	'absorb'		: ['take in fluids', 'soak up'],
	'abstain from'	: ["don't", "don't use", "don't have", "go without"],
	'accompany'		: ['go along with', 'come with'],
	'accomplish'	: ['carry out', 'do'],
	'accordingly'	: ['so', 'for that reason', 'as a result'] ,
	'accrue'		: ['add', 'gain', 'build up'],
	'accumulate'	: ['correct', 'exact', 'right'],
	'acquire'		: ['get'],
	'activate'		: ['begin', 'start'],
	'acute'			: ['sudden', 'new', 'recent'],
	'addictive'		: ['habit-forming']
}

bodyparts = [
	'head',
	'forehead',
	'eyeball',
	'eye socket',
	'eye whites',
	'eye color ring',
	'eye hole',
	'ears',
	'ear canal',
	'ear drum',
	'nose bridge',
	'nostrils',
	'cheeks',
	'cheek bone',
	'lips',
	'tongue',
	'mouth',
	'gums',
	'upper jaw',
	'lower jaw',
	'chin',
	'teeth',
	'voice box',
	"adam's apple",
	'pit of throat',
	'swallow pipe',
	'collar bones',
	'shoulder blade',
	'chest bone',
	'ribs',
	'rib joints',
	'pit of stomach',
	'navel',
	'loins',
	'bladder area',
	'womb',
	'foreskin',
	'balls',
	'nuts',
	'bum',
	'butt',
	'neck spine',
	'mid back spine',
	'lower back spine',
	'spine bones',
	'tailbone',
	'shoulder',
	'armpit',
	'upper arm bone',
	'elbow',
	'funny bone',
	'forearm outer bone',
	'forearm inner bone',
	'wrist',
	'hand',
	'fingers',
	'hips',
	'upper leg muscles',
	'upper leg bone',
	'knee cap',
	'shin bone',
	'ankle',
	'heel',
	'foot arch',
	'toes',
	'great toe',
	'trunk',
	'breasts',
	'nipples',
	'brain',
	'heart',
	'lungs',
	'liver',
	'kidneys',
	'digestive tract',
	'skin',
	'baldness'
]

key_terms = [
	'virus',
	'epidemia',
	'enfermos',
	'hanta',
	'viral',
	'territorio',
	'pneumonia',
	'sangre',
	'ratones',
	'cardiopulmonar',
	'vacuna',
	'campos',
	'provincial',
	'hantavirus',
	'tosse',
	'nariz',
	'estornudar',
	'abdominal',
	'lluvia',
	'renal',
	'paciente',
	'transmissor',
	'lixo',
	'criaderos',
	'respiratorias',
	'manos',
	'boca',
	'rural',
	'musculares',
	'roedores',
	'rash',
	'high fever',
	'joint pain',
	'nausea',
	'vomit',
	'photophobia',
	'arthralgia',
	'Dengue',
	'cough'
]

total_terms = bodyparts + key_terms
